export const environment = {
  production: true,
  name: 'admin.com',
  domain: 'admin.clothigo.com',
  baseLink: 'https://admin.clothigo.com',
  paymentBaseLink: 'https://clothigo.com',
  apiBaseLink: 'https://api.clothigo.com',
  ftpBaseLink: 'https://api.clothigo.com',
  ftpPrefixPath: 'https://api.clothigo.com/api/upload/images',
  ftpPrefix: '/api',
  userLoginUrl: 'login',
  userBaseUrl: '',
  appBaseUrl: '/',
  adminBaseUrl: '',
  adminLoginUrl: 'login',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  vendorLoginUrl: 'login',
  vendorBaseUrl: '',
  vendorSecretKey: 'saleecoMVendoRLogiNSecreT2025',
  VERSION: 2,
  deploymentType: 'default', // 'default' = show all features, any other value = hide subscription/support features
};
